### ISSUE TITLE
5V incompatible 

### ISSUE THREAD

**Issue by benlawraus** [adafruit/Adafruit_Python_LED_Backpack#12]
When I connect the red LED to 3.3V, sevensegment_test.py runs perfectly. However the display is too dim using the raspberry pi model 3, so I need 5V. When I connect to 5V, I get a input/output error. in write_i2c_block_data

**Comment by caternuson** [comment]
This is a hardware issue, not a software issue. By powering with 5V you are changing the logic level of the i2c bus to 5V also. You will need to use a logic level converter to run the display this way.
