### ISSUE TITLE
error in print_number_str() when executed by python3

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_Python_LED_Backpack#17]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  **INSERT PLATFORM/OPERATING
  SYSTEM HERE**

Rasberry Pi with Raspbian
4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

- Python version (run `python -version` or `python3 -version`):  **INSERT PYTHON
  VERSION HERE**

Python 3.4.2

- Error message you are receiving, including any Python exception traces:  **INSERT
  ERROR MESAGE/EXCEPTION TRACES HERE***

$ python3 ./AlphaNumTest.py
Traceback (most recent call last):
  File "./AlphaNumTest.py", line 101, in <module>
    display.print_number_str("22.", justify_right=False)
  File "/usr/local/lib/python3.4/dist-packages/Adafruit_LED_Backpack-1.8.1-py3.4.egg/Adafruit_LED_Backpack/AlphaNum4.py", line 183, in print_number_str
TypeError: translate() takes exactly one argument (2 given)

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): **LIST REPRO STEPS BELOW**

Code executes fine with python2. I have not found a correction for python3.

**Comment by dudesick** [comment]
go into the AlphaNum4.py file and delete the line containing "translate". Then replace with

`table = str.maketrans(dict.fromkeys('.'))
length = len(value.translate(table))`

be sure that tabs are in place. this worked for me. pretty sure the 7-segment library has this issue too. same fix though. 

hope this helps, cheers

**Comment by bluejakester** [comment]
@dudesick Thanks for posting this. I've implemented and so far no issues as before.

**Comment by bluejakester** [comment]
@dudesick Thank you for posting this!

**Comment by caternuson** [comment]
Hello. We are archiving this repo. The new library is here:
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33
For use with Raspberry Pi, you'll need to install Blinka support but then you can just pip3 that repo to install support:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-sensors-and-devices
