### ISSUE TITLE
No module named Adafruit_LED_Backpack 

### ISSUE THREAD

**Issue by Thermo96** [adafruit/Adafruit_Python_LED_Backpack#28]
Hello,

Recently, I just bought a 4 Digit-7Segment Display from Adafruit. After connecting the LED pack with my Raspberry Pi 2 I just wanted to start an example code, which is part of the official Code package. Unfortunately, I was not able to run the example Code due to an error, which I could not solve on my one.  I would really appreciate, if someone give me a hint or an advise how I can handle this.

pi@raspberrypi ~ $ ls
Adafruit_Python_LED_Backpack  Documents  python_games  Scratch
Desktop                       Downloads  Schrott
pi@raspberrypi ~ $ cd Adafruit_Python_LED_Backpack
pi@raspberrypi ~/Adafruit_Python_LED_Backpack $ ls
Adafruit_LED_Backpack  examples  ez_setup.py  LICENSE  README.md  setup.py
pi@raspberrypi ~/Adafruit_Python_LED_Backpack $ cd examples
pi@raspberrypi ~/Adafruit_Python_LED_Backpack/examples $ ls
alphanum4_test.py           ex_7segment_clock.py  sevensegment_test.py
bicolor_bargraph24_test.py  matrix8x16_test.py
bicolor_matrix8x8_test.py   matrix8x8_test.py
pi@raspberrypi ~/Adafruit_Python_LED_Backpack/examples $ sudo python ex_7segment_clock.py
Traceback (most recent call last):
  File "ex_7segment_clock.py", line 6, in <module>
    from Adafruit_LED_Backpack import SevenSegment
ImportError: No module named Adafruit_LED_Backpack
pi@raspberrypi ~/Adafruit_Python_LED_Backpack/examples $ ^C

Thank you very much in advance!

**Comment by DieselDragon** [comment]
You probably want the **Adafruit_LED_Backpack** library (Different source tree) [Here](https://github.com/adafruit/Adafruit_LED_Backpack)

Hope this helps! :-)

**Comment by ladyada** [comment]
hiya - the best thing to do is actually use our new circuitpython library here!
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33
you'll need to install Blinka support but then you can just pip3 that repo to install support
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-sensors-and-devices
