### ISSUE TITLE
Need to change SDA pins

### ISSUE THREAD

**Issue by sekisek** [adafruit/Adafruit_Python_LED_Backpack#29]
Everything is working great when I use SDA1/SCL1 (pins NUMBERS 3/5 GPIO 8/9 RPI 3 model B)  but I need to use other pins instead.

I thought on using pin NUMBERS 27/28 SDA0/SCL0.

Can I? 
please help.

thanks!

**Comment by caternuson** [comment]
You can't change hardware I2C pin locations. But you can setup software I2C on pretty much any GPIO pin using the `i2c-gpio` overlay.
