### ISSUE TITLE
I want to make a PR to extend character set for SevenSegment.py

### ISSUE THREAD

**Issue by joshgc** [adafruit/Adafruit_Python_LED_Backpack#30]
Hi all,

I have a working version of SevenSegment.py in my local branch that adds a variety of new characters to the seven segment display driver. Its backwards compatible, doesn't add any significant overhead (loading on my RPi0W still takes < 150 microseconds) and works correctly when inverted. Also I added some comments about the logic behind the driver just to help the next reader be informed about how it works.

Do I have to do anything special to submit the PR? I'm getting a 403 from my git push.

Josh

**Comment by joshgc** [comment]
Ah, sorry, so as an example now messages like this are possible:

'HELP'
'59\degC'
'Err7'

**Comment by caternuson** [comment]
Hello. We are archiving this repo. The new library is here:
https://github.com/adafruit/Adafruit_CircuitPython_HT16K33
