### ISSUE TITLE
Can't subclass SevenSegment?

### ISSUE THREAD

**Issue by rolfyone** [adafruit/Adafruit_Python_LED_Backpack#4]
I'm new to python so hopefully it's just a 'me' thing...

I've tried subclassing SevenSegment, and always get an error about expecting 2 arguments but got 3...

Basically I've just done:
```

from Adafruit_LED_Backpack import SevenSegment

class ClockDisplay(SevenSegment):

	def __init__(self, **kwargs):
		super(ClockDisplay, self).__init__(**kwargs)
```

and that seems to fail. (this is from memory, i'll double check the code when i get home - i did have some other functions too, just trying to simplify the issue as much as i can)

What am I doing wrong?
I'd like to subclass it so that I can extend some of the functionality, and I'm hoping once I get it write to put a pull request in, but it's hard when i can't get this bit to work

If i run from the dev folder, and use 'from SevenSegment import SevenSegment', the code seems to work...

**Comment by jakekarnes42** [comment]
Hi rolfyone, 

Did you run the setup script? Check the readme for this project. There are a few steps (assuming Debian system):
1. sudo apt-get update
2. sudo apt-get install build-essential python-dev
3. sudo apt-get install python-smbus python-imaging
4. sudo python setup.py install 

Possibly you missed step 4?

Other than that, I would double check that the code you provided from memory really matches up with the code you are trying to execute.

**Comment by rolfyone** [comment]
I've definitely run step 4. I've got anther script that is using the same import and working (without subclassing) just using SevenSegment like in the example script.
I was trying to encapsulate setting other aspects of the metacharacter (center colon, left colon dots) within this subclass, as well as having it write a 12 hour clock... Maybe I should just hack it straight into seven segment i guess, I just figured that subclassing would let me implement all the bits i need without updating the library initially and having to make install all the time...

**Comment by jakekarnes42** [comment]
Give this a try:
```
from Adafruit_LED_Backpack import SevenSegment

class ClockDisplay(SevenSegment.SevenSegment):
   ...
```

**Comment by rolfyone** [comment]
Thanks for that, that was precisely the problem! I'm sorry to raise an issue and it was something silly :( I was assuming it was something I was doing wrong...

**Comment by tdicola** [comment]
Oh no problem glad you got the issue resolved, thanks jakekarnes42 for jumping in to help!
